//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSP7_pw
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int deliveryID { get; set; }
        public decimal distanceCost { get; set; }
        public string vehicleType { get; set; }
        public string notes { get; set; }
    }
}
