//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSP7_pw
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int itemID { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public decimal weight { get; set; }
        public decimal costPrice { get; set; }
        public decimal retailPrice { get; set; }
        public int supplierID { get; set; }
        public bool active { get; set; }
        public string notes { get; set; }
        public int caseSize { get; set; }
    }
}
