//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSP7_pw
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bullseyedbEntities : DbContext
    {
        public bullseyedbEntities()
            : base("name=bullseyedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<posn> posns { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<site> sites { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<txn> txns { get; set; }
        public virtual DbSet<txnaudit> txnaudits { get; set; }
        public virtual DbSet<txnitem> txnitems { get; set; }
        public virtual DbSet<txnstatu> txnstatus { get; set; }
        public virtual DbSet<txntype> txntypes { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    }
}
