//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSP7_pw
{
    using System;
    using System.Collections.Generic;
    
    public partial class txn
    {
        public int txnID { get; set; }
        public int siteIDTo { get; set; }
        public int siteIDFrom { get; set; }
        public string status { get; set; }
        public System.DateTime shipDate { get; set; }
        public string txnType { get; set; }
        public string barCode { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<int> deliveryID { get; set; }
        public Nullable<bool> emergencyDelivery { get; set; }
    }
}
