//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSP7_pw
{
    using System;
    using System.Collections.Generic;
    
    public partial class txnaudit
    {
        public int txnAuditID { get; set; }
        public int txnID { get; set; }
        public string txnType { get; set; }
        public string status { get; set; }
        public System.DateTime txnDate { get; set; }
        public int SiteID { get; set; }
        public Nullable<int> deliveryID { get; set; }
    }
}
