//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSP7_pw
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public string vehicleType { get; set; }
        public decimal maxWeight { get; set; }
        public decimal HourlyTruckCost { get; set; }
        public decimal costPerKem { get; set; }
        public string notes { get; set; }
    }
}
